#!/bin/bash
# 
# defs.sh
# Parameters used by all programs
#
# 201301 - Christian D Freitas


#Database name
DATABASE=db.rrd
#Modem address
MODEM_ADDR= 
#Modem page (where to get statistics)
MODEM_DSL_PAGE="/index.cgi?page=statdsl"
#Modem admin account
MODEM_USER=
#Modem password
MODEM_PASS=

#Arrays (avoiding multidimensional arrays!!)

#Generate graphics only for parameters which index is present in the ARR_IDXS list
ARR_IDXS="0 1 6 7 8 9"
#Last array index
ARR_LAST_IDX=13

#Array format
#ARR_DATABASE_DS_NAME[] = DS_name of parameter (rrdtool)
#ARR_GRAPH_TITLE[]= Graphic title  (rrdgraph)
#ARR_GRAPH_VERTICAL_LABEL[]= (rrdgraph)
#ARR_GRAPH_FILENAME[]= filename (generated by rrdgraph)
#ARR_MODEM_STRING[]=parameter search string
#   All modem parameters (ADSL statistcs) are gathered from the html file. The search string is (somewhat) used  to locate the parameter
#VALUE_FROM_HTML[]= Value gathered from the html file (or from tespeed.py

ARR_DATABASE_DS_NAME[0]="Speed_Download"
ARR_GRAPH_TITLE[0]="Downstream Speed"
ARR_GRAPH_VERTICAL_LABEL[0]="Mbps"
ARR_GRAPH_FILENAME[0]="downspeed"
ARR_MODEM_STRING[0]="Downstream Current Rate"
VALUE_FROM_HTML[0]=0

ARR_DATABASE_DS_NAME[1]="Speed_Upload"
ARR_GRAPH_TITLE[1]="Upstream Speed"
ARR_GRAPH_VERTICAL_LABEL[1]="Mbps"
ARR_GRAPH_FILENAME[1]="uploadspeed"
ARR_MODEM_STRING[1]="Upstream Current Rate"
VALUE_FROM_HTML[1]=0

ARR_DATABASE_DS_NAME[2]="Mdm_Down_C_Rate"
ARR_GRAPH_TITLE[2]="Downstream Current Rate"
ARR_GRAPH_VERTICAL_LABEL[2]="Mbps"
ARR_GRAPH_FILENAME[2]="downcurrrate"
ARR_MODEM_STRING[2]="Downstream Current Rate"
VALUE_FROM_HTML[2]=0

ARR_DATABASE_DS_NAME[3]="Mdm_Up_C_Rate"
ARR_GRAPH_TITLE[3]="Upstream Current Rate"
ARR_GRAPH_VERTICAL_LABEL[3]="Mbps"
ARR_GRAPH_FILENAME[3]="upcurrrate"
ARR_MODEM_STRING[3]="Upstream Current Rate"
VALUE_FROM_HTML[3]=0

ARR_DATABASE_DS_NAME[4]="Mdm_Down_Max_Rate"
ARR_GRAPH_TITLE[4]="Downstream Max Rate"
ARR_GRAPH_VERTICAL_LABEL[4]="Mbps"
ARR_GRAPH_FILENAME[4]="downmaxrate"
ARR_MODEM_STRING[4]="Downstream Max Rate"
VALUE_FROM_HTML[4]=0

ARR_DATABASE_DS_NAME[5]="Mdm_Up_Max_Rate"
ARR_GRAPH_TITLE[5]="Upstream Max Rate"
ARR_GRAPH_VERTICAL_LABEL[5]="Mbps"
ARR_GRAPH_FILENAME[5]="upmaxrate"
ARR_MODEM_STRING[5]="Upstream Max Rate"
VALUE_FROM_HTML[5]=0

ARR_DATABASE_DS_NAME[6]="Mdm_Down_Noise_M"
ARR_GRAPH_TITLE[6]="Downstream Noise Margin"
ARR_GRAPH_VERTICAL_LABEL[6]="dB"
ARR_GRAPH_FILENAME[6]="downnoisemargin"
ARR_MODEM_STRING[6]="Downstream Noise Margin"
VALUE_FROM_HTML[6]=0

ARR_DATABASE_DS_NAME[7]="Mdm_Up_Noise_M"
ARR_GRAPH_TITLE[7]="Upstream Noise Margin"
ARR_GRAPH_VERTICAL_LABEL[7]="dB"
ARR_GRAPH_FILENAME[7]="upnoisemargin"
ARR_MODEM_STRING[7]="Upstream Noise Margin"
VALUE_FROM_HTML[7]=0

ARR_DATABASE_DS_NAME[8]="Mdm_Down_Att"
ARR_GRAPH_TITLE[8]="Downstream Attenuation"
ARR_GRAPH_VERTICAL_LABEL[8]="dB"
ARR_GRAPH_FILENAME[8]="downatt"
ARR_MODEM_STRING[8]="Downstream Attenuation"
VALUE_FROM_HTML[8]=0

ARR_DATABASE_DS_NAME[9]="Mdm_Up_Att"
ARR_GRAPH_TITLE[9]="Upstream Attenuation"
ARR_GRAPH_VERTICAL_LABEL[9]="dB"
ARR_GRAPH_FILENAME[9]="upatt"
ARR_MODEM_STRING[9]="Upstream Attenuation"
VALUE_FROM_HTML[9]=0

ARR_DATABASE_DS_NAME[10]="Mdm_Down_Power"
ARR_GRAPH_TITLE[10]="Downstream Power"
ARR_GRAPH_VERTICAL_LABEL[10]="dbm"
ARR_GRAPH_FILENAME[10]="downpower"
ARR_MODEM_STRING[10]="Downstream Power"
VALUE_FROM_HTML[10]=0

ARR_DATABASE_DS_NAME[11]="Mdm_Up_Power"
ARR_GRAPH_TITLE[11]="Upstream Power"
ARR_GRAPH_VERTICAL_LABEL[11]="dbm"
ARR_GRAPH_FILENAME[11]="uppower"
ARR_MODEM_STRING[11]="Upstream Power"
VALUE_FROM_HTML[11]=0

ARR_DATABASE_DS_NAME[12]="Mdm_Down_FEC"
ARR_GRAPH_TITLE[12]="Downstream FEC"
ARR_GRAPH_VERTICAL_LABEL[12]="corrected blocks"
ARR_GRAPH_FILENAME[12]="downfec"
ARR_MODEM_STRING[12]="Downstream FEC"
VALUE_FROM_HTML[12]=0

ARR_DATABASE_DS_NAME[13]="Mdm_Up_FEC"
ARR_GRAPH_TITLE[13]="Upstream FEC"
ARR_GRAPH_VERTICAL_LABEL[13]="corrected blocks"
ARR_GRAPH_FILENAME[13]="upfec"
ARR_MODEM_STRING[13]="Upstream FEC"
VALUE_FROM_HTML[13]=0
