# 
# extract_html_data.py
# Extracts the values from html file (statistics values generated by the PowerBox Modem)
#
# 201301 - Christian D Freitas

from HTMLParser import HTMLParser
import sys

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    strdata = []
    def handle_data(self, data):
        #Ignore space (as first char)
        if data[0] != ' ':
            # Alguns campos "data" possuem a unidade de medida (ex: 10 dB). Como a unidade eh separada por espacco, o split separa a string e somente o valor e adicionado ao array strdata
            # Gets only value (ignores measurement units)
            self.strdata.append(data.split(' ')[0])


# instantiate the parser and fed it some HTML
parser = MyHTMLParser()
parser.feed(sys.stdin.readlines()[0].strip('\n'))

print sys.argv[1]+"="+parser.strdata[1]


#O html parser encontra duas strings (data), que sao armazenados em um array
# 0 - Uma string que descreve o significado do campo
# 1 - Uma string que contem o valor do campo
